exports.skills = {
    common: [
        'Kỹ năng giao tiếp',
        'Kỹ năng quản lý thời gian',
        'Kỹ năng làm việc nhóm',
        'Kỹ năng giải quyết vấn đề',
        'Nhanh nhẹn',
        'Tỉ mỉ',
        'Khéo léo',
    ],
    IT: [
        'ReactJS',
        'NodeJS',
        'Java',
        'PHP',
        'Python',
        'Golang',
        'ASP.NET',
        'C++',
        'HTML5',
        'CSS3',
        '.NET',
        'Spring Boot',
        'Laravel',
        'MVC',
        'Android',
        'Flutter',
        'IOS',
        'Kotlin',
        'OOP',
        'PostgreSql',
        'Ruby',
        'SQL',
        'NoSQL',
        'Angular',
        'VueJS',
        'AWS',
        'Cloud',
        'Embeded',
        'Swift',
        'Tester',
        'DevOps',
        'English',
        'JQuery',
        'MySQL',
        'Typescript',
    ],
    'Y tế': [
        'Kiến thức y khoa',
        'Kiến thức về công nghệ y tế',
        'Bằng cử nhân Y sĩ',
        'Bằng cử nhân Điều dưỡng',
        'Bằng Thạc sĩ Y tế',
        'Chứng chỉ chuyên môn',
    ],
    'Đồ họa': [
        'Kỹ năng sáng tạo',
        'Kỹ năng hình ảnh và màu sắc',
        'Kỹ năng sử dụng công cụ thiết kế',
        'Photoshop',
        'Adobe Premiere',
        'Auto Card',
        'UI/UX',
        'Thiết kế giao diện người dùng',
    ],
    'Sự kiện': [
        'Kỹ năng quản lý thông tin',
        'Kỹ năng viết và biên tập',
        'Kỹ năng quảng cáo',
        'Kỹ năng quản lý dự án',
        'Khả năng thích nghi',
        'Khả năng ứng xử',
    ],
    'Tài chính': [
        'Kiến thức về tài chính',
        'Kiến thức về kế toán',
        'Phân tích tài chính',
        'Kiến thức về thị trường tài chính',
        'Kỹ năng quản lý rủi ro',
        'Chứng chỉ đầu tư',
    ],
    Sales: [
        'Kỹ năng bán hàng',
        'Kỹ năng quảng cáo và truyền thông',
        'Kỹ năng phân tích dữ liệu',
        'Khả năng chịu áp lực',
        'Kỹ năng về tâm lý học',
    ],
    Marketing: [
        'Phân tích dữ liệu',
        'Nắm bắt tâm lý khách hàng',
        'Định hướng chiến lược và quản lý dự án',
        'Nhạy bén với thị trường',
        'Kỹ năng lập kế hoạch',
        'Kỹ năng thiết kế',
        'Sáng tạo nội dung',
    ],
    Content: [
        'Phân tích thương hiệu',
        'SEO',
        'Xây dựng ý tưởng và nội dung',
        'Sản xuất nội dung',
        'Khai thác ý tưởng',
        'Sản xuất video',
        'Chỉnh sửa hình ảnh/video',
        'Quảng bá nội dung',
    ],
};
